branches:
  only:
  - master
before_install:
  - sudo add-apt-repository ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs-snapshot
  - which emacs
  - which emacs-snapshot
script: bash .travis/build_site.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: deploy
notifications:
  email:
    on_success: never
    on_failure: never
